// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: dag.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerkleNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash  string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Path  string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type  string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Data  string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Links []string `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *MerkleNode) Reset() {
	*x = MerkleNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerkleNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleNode) ProtoMessage() {}

func (x *MerkleNode) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleNode.ProtoReflect.Descriptor instead.
func (*MerkleNode) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleNode) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MerkleNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MerkleNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MerkleNode) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MerkleNode) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

type MerkleRoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root     string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	TreeRoot string `protobuf:"bytes,2,opt,name=treeRoot,proto3" json:"treeRoot,omitempty"`
	DagRoot  string `protobuf:"bytes,3,opt,name=dagRoot,proto3" json:"dagRoot,omitempty"`
}

func (x *MerkleRoot) Reset() {
	*x = MerkleRoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerkleRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRoot) ProtoMessage() {}

func (x *MerkleRoot) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRoot.ProtoReflect.Descriptor instead.
func (*MerkleRoot) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{1}
}

func (x *MerkleRoot) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *MerkleRoot) GetTreeRoot() string {
	if x != nil {
		return x.TreeRoot
	}
	return ""
}

func (x *MerkleRoot) GetDagRoot() string {
	if x != nil {
		return x.DagRoot
	}
	return ""
}

type Reciept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root *MerkleRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *Reciept) Reset() {
	*x = Reciept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reciept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reciept) ProtoMessage() {}

func (x *Reciept) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reciept.ProtoReflect.Descriptor instead.
func (*Reciept) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{2}
}

func (x *Reciept) GetRoot() *MerkleRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

type SignedReciept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root      *Reciept `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Signature string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedReciept) Reset() {
	*x = SignedReciept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedReciept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedReciept) ProtoMessage() {}

func (x *SignedReciept) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedReciept.ProtoReflect.Descriptor instead.
func (*SignedReciept) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{3}
}

func (x *SignedReciept) GetRoot() *Reciept {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SignedReciept) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dag_proto protoreflect.FileDescriptor

var file_dag_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x72, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x65, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x65, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x67, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x67, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x2f, 0x0a,
	0x07, 0x52, 0x65, 0x63, 0x69, 0x65, 0x70, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65,
	0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x50,
	0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x63, 0x69, 0x65, 0x70, 0x74, 0x12,
	0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x65, 0x70, 0x74, 0x52, 0x04, 0x72, 0x6f,
	0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xee, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x72, 0x6b, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x1a, 0x0e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x65, 0x70, 0x74, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x63, 0x69, 0x65, 0x70, 0x74,
	0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x65,
	0x63, 0x69, 0x65, 0x70, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x6c, 0x69, 0x62, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dag_proto_rawDescOnce sync.Once
	file_dag_proto_rawDescData = file_dag_proto_rawDesc
)

func file_dag_proto_rawDescGZIP() []byte {
	file_dag_proto_rawDescOnce.Do(func() {
		file_dag_proto_rawDescData = protoimpl.X.CompressGZIP(file_dag_proto_rawDescData)
	})
	return file_dag_proto_rawDescData
}

var file_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dag_proto_goTypes = []interface{}{
	(*MerkleNode)(nil),    // 0: grpc.MerkleNode
	(*MerkleRoot)(nil),    // 1: grpc.MerkleRoot
	(*Reciept)(nil),       // 2: grpc.Reciept
	(*SignedReciept)(nil), // 3: grpc.SignedReciept
	(*Response)(nil),      // 4: grpc.Response
}
var file_dag_proto_depIdxs = []int32{
	1, // 0: grpc.Reciept.root:type_name -> grpc.MerkleRoot
	2, // 1: grpc.SignedReciept.root:type_name -> grpc.Reciept
	1, // 2: grpc.MerkleService.SendMerkleRoot:input_type -> grpc.MerkleRoot
	0, // 3: grpc.MerkleService.SendMerkleNode:input_type -> grpc.MerkleNode
	1, // 4: grpc.MerkleService.NotifyCompletion:input_type -> grpc.MerkleRoot
	3, // 5: grpc.MerkleService.SendSignedReciept:input_type -> grpc.SignedReciept
	4, // 6: grpc.MerkleService.SendMerkleRoot:output_type -> grpc.Response
	4, // 7: grpc.MerkleService.SendMerkleNode:output_type -> grpc.Response
	2, // 8: grpc.MerkleService.NotifyCompletion:output_type -> grpc.Reciept
	4, // 9: grpc.MerkleService.SendSignedReciept:output_type -> grpc.Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dag_proto_init() }
func file_dag_proto_init() {
	if File_dag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerkleNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerkleRoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reciept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedReciept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dag_proto_goTypes,
		DependencyIndexes: file_dag_proto_depIdxs,
		MessageInfos:      file_dag_proto_msgTypes,
	}.Build()
	File_dag_proto = out.File
	file_dag_proto_rawDesc = nil
	file_dag_proto_goTypes = nil
	file_dag_proto_depIdxs = nil
}
